Volatile patch (#2269)
Current reduced precision in our runtime header relies on implicit copy
constructor & copy assignment operator.
`T::T(const T&)` and `T& T::operator=(const T&)`.

Unfortunately, this would not handle cases where we have `volatile`
instances. For generated code with: `*(volatile __half*)&T10[i3] =
T4[0];` or `T4[0] = *(volatile __half*)&T10[i3];`, we'll run into errors
in nvrtc
```
error: no operator "=" matches these operands
operand types are: volatile <unnamed>::__half = <unnamed>::__half
```

This PR added overload for volatile instances listed below (Thanks to
@jacobhinkle for listing it out):
i.e. this should cover cases 
for copy constructor
`volatile` / `non-volatile`
for copy assignment operator
`non-volatile = non-volatile` / `non-volatile = volatile` / `volatile =
non-volatile` / `volatile = volatile`
```
T::T(const T&);
T::T(const T&&);
T::T(const volatile T&);
T::T(const volatile T&&);
void T::operator=(const T&);
void T::operator=(const T&&);
void T::operator=(const volatile T&);
void T::operator=(const volatile T&&);
void T::operator=(const T&) volatile;
void T::operator=(const T&&) volatile;
void T::operator=(const volatile T&) volatile;
void T::operator=(const volatile T&&) volatile;
```

- Note 1:
For each volatile argument, we need overload for `const volatile T&` and
`const volatile T&&`, because rvalue can only bind to const non-volatile
lvalue reference.
This could happen with a example like this: `T4[0] = predicate ?
*(volatile __half*)&T10[i3] : 1.5;` where ternary operator would resolve
to an volatile rvalue.
Technically, `const T&` could also be bound by rvalue `T&&`. But due to
the overload with `const volatile T&&`, which precedes `const T&`, we
decided to also add an overload of `const T&&` to avoid that. Thanks to
@naoyam for catching this one.

- Note 2:
I explicitly changed the copy assignment operator to NOT return
reference to self.

I'm seeing gcc warning in my toy example when copy assignment returns a
volatile lvalue reference when it's trivially used as `*(volatile
XXX*)s_ptr = s_instance;`. `implicit dereference will not access object
of type `volatile XXX` in statement`.

This is really annoying (for reference about the warning, see this:
https://gcc.gnu.org/onlinedocs/gcc-4.0.4/gcc/Volatiles.html)
IIUC, we don't use the return from copy assignment operator anyway. I'm
happy to revisit this one.