Build fix (#579)
The fix updated test code to explicitly use int64_t, one of types
defined in variant representing ScalarValue.

An alternative fix is adding `int` to the list of types supported by
ScalarType
([location](https://github.com/NVIDIA/Fuser/blob/071c9522bfe9f57bdd9858177b15a56bad6caeba/csrc/scalar_value.h#L166))
although it seems redundant given that `int64_t` belong to the list
hence test fix.

----

Issue happened for gcc9.4, default toolchain on Ubuntu 20.04. The error
log without the fix looks like this:
```
Fuser/csrc/dynamic_type.h: In instantiation of ‘constexpr nvfuser::DynamicType<Containers, Ts>::DynamicType(const T&) [with T = int; Containers = nvfuser::Containers<std::vector, nvfuser::Struct>; Ts = {std::complex<double>, double, long int, bool, nvfuser::Pointer}]’:
Fuser/test/test_evaluator.cpp:363:43:   required from here
Fuser/csrc/dynamic_type.h:213:55: error: no matching function for call to ‘std::variant<std::monostate, std::complex<double>, double, long int, bool, nvfuser::Pointer, std::vector<nvfuser::DynamicType<nvfuser::Containers<std::vector, nvfuser::Struct>, std::complex<double>, double, long int, bool, nvfuser::Pointer>, std::allocator<nvfuser::D
ynamicType<nvfuser::Containers<std::vector, nvfuser::Struct>, std::complex<double>, double, long int, bool, nvfuser::Pointer> > >, nvfuser::Struct<nvfuser::DynamicType<nvfuser::Containers<std::vector, nvfuser::Struct>, std::complex<double>, double, long int, bool, nvfuser::Pointer> > >::variant(const int&)’
  213 |   constexpr DynamicType(const T& value) : value_(value) {}
      |                                                       ^
In file included from pytorch/third_party/googletest/googletest/include/gtest/internal/gtest-port.h:2377,
                 from pytorch/third_party/googletest/googlemock/include/gmock/internal/gmock-port.h:56,
                 from pytorch/third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:46,
                 from pytorch/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:271,
                 from Fuser/test/test_evaluator.cpp:9:
/usr/include/c++/9/variant:1351:2: note: candidate: ‘template<long unsigned int _Np, class _Up, class ... _Args, class _Tp, class> constexpr std::variant<_Types>::variant(std::in_place_index_t<_Np>, std::initializer_list<_Up>, _Args&& ...)’
 1351 |  variant(in_place_index_t<_Np>, initializer_list<_Up> __il,
      |  ^~~~~~~
/usr/include/c++/9/variant:1351:2: note:   template argument deduction/substitution failed:
In file included from Fuser/csrc/scalar_value.h:12,
                 from Fuser/csrc/ir/base_nodes.h:15,
                 from Fuser/csrc/ir/all_nodes.h:10,
                 from Fuser/csrc/device_lower/analysis/sync_information.h:10,
                 from Fuser/csrc/kernel.h:12,
                 from Fuser/csrc/codegen.h:11,
                 from Fuser/test/utils.h:10,
                 from Fuser/test/test_evaluator.cpp:12:
Fuser/csrc/dynamic_type.h:213:55: note:   mismatched types ‘std::in_place_index_t<_Idx>’ and ‘int’
  213 |   constexpr DynamicType(const T& value) : value_(value) {}
      |                                                       ^
In file included from pytorch/third_party/googletest/googletest/include/gtest/internal/gtest-port.h:2377,
                 from pytorch/third_party/googletest/googlemock/include/gmock/internal/gmock-port.h:56,
                 from pytorch/third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:46,
                 from pytorch/third_party/googletest/googlemock/include/gmock/gmock-matchers.h:271,
                 from Fuser/test/test_evaluator.cpp:9:
/usr/include/c++/9/variant:1340:2: note: candidate: ‘template<long unsigned int _Np, class ... _Args, class _Tp, class> constexpr std::variant<_Types>::variant(std::in_place_index_t<_Np>, _Args&& ...)’
 1340 |  variant(in_place_index_t<_Np>, _Args&&... __args)
      |  ^~~~~~~
/usr/include/c++/9/variant:1340:2: note:   template argument deduction/substitution failed:
In file included from Fuser/csrc/scalar_value.h:12,
                 from Fuser/csrc/ir/base_nodes.h:15,
                 from Fuser/csrc/ir/all_nodes.h:10,
                 from Fuser/csrc/device_lower/analysis/sync_information.h:10,
                 from Fuser/csrc/kernel.h:12,
                 from Fuser/csrc/codegen.h:11,
                 from Fuser/test/utils.h:10,
                 from Fuser/test/test_evaluator.cpp:12:
Fuser/csrc/dynamic_type.h:213:55: note:   mismatched types ‘std::in_place_index_t<_Idx>’ and ‘int’
  213 |   constexpr DynamicType(const T& value) : value_(value) {}
      |                                                       ^
```

Co-authored-by: Gao, Xiang <qasdfgtyuiop@gmail.com>