remove unused `hash_scalars_` (#259)
In my dirty local environment with clang-14, I needed this attribute.

```
[4/103] Building CXX object CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o
FAILED: CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o
/usr/bin/c++ -DTORCH_CUDA_BUILD_MAIN_LIB -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -Dnvfuser_codegen_EXPORTS -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/benchmark/include -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/third_party/gloo -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/csrc -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/build/include -I/home/mkozuki/ghq/github.com/NVIDIA/fuser/../third_party/flatbuffers/include -isystem /home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/googletest/googlemock/include -isystem /home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/googletest/googletest/include -isystem /home/mkozuki/ghq/github.com/NVIDIA/fuser/cmake/../third_party/flatbuffers/include -isystem /usr/local/cuda-12.0/include -isystem /home/mkozuki/ghq/github.com/crcrpar/torch-3/torch/include -isystem /home/mkozuki/ghq/github.com/crcrpar/torch-3/torch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -DNDEBUG -std=gnu++17 -fPIC -Wall -Wno-unused-function -DTORCH_CUDA_BUILD_MAIN_LIB -Werror -D_GLIBCXX_USE_CXX11_ABI=1 -MD -MT CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o -MF CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o.d -o CMakeFiles/nvfuser_codegen.dir/csrc/kernel_cache.cpp.o -c /home/mkozuki/ghq/github.com/NVIDIA/fuser/csrc/kernel_cache.cpp
In file included from /home/mkozuki/ghq/github.com/NVIDIA/fuser/csrc/kernel_cache.cpp:8:
/home/mkozuki/ghq/github.com/NVIDIA/fuser/csrc/kernel_cache.h:350:8: error: private field 'hash_scalars_' is not used [-Werror,-Wunused-private-field]
  bool hash_scalars_ = false;
       ^
1 error generated.
```

---------

Signed-off-by: Masaki Kozuki <mkozuki@nvidia.com>