Delete an unnecessary copy constructor.
Declaring a copy constructor should come with a copy constructor as
well. Compilation with clang resulted in:

```
error: definition of implicit copy assignment operator for
'DynamicTransformInitialInfo' is deprecated because it has a
user-declared copy constructor [-Werror,-Wdeprecated-copy]
  DynamicTransformInitialInfo(const DynamicTransformInitialInfo& other)
  =
    ^
    /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/optional:789:21:
    note: in implicit copy assignment operator for
    'nvfuser::DynamicTransformInitialInfo' first required here
                this->_M_get() = std::forward<_Up>(__u);
```