Use std::optional instead of direct default argument for LaunchParams (#5980)
* LaunchParams is constructed when nvfuser_direct is loaded because it a
default argument for `KernelExecutor`.
* It uses at::cuda::getCurrentDeviceProperties(), which can cause `CUDA
error: CUDA driver version is insufficient for CUDA runtime version`
when importing `nvfuser_direct`.
* The `smoke_test` check for this, so the PR uses `std::optional`
instead of direct default argument for `LaunchParams`