Disable stride check for size one (#5677)
This PR fixes the following error:

```py
from nvfuser_direct import FusionDefinition, DataType
import torch

def nvfuser_fusion(fd : FusionDefinition) -> None :
    tv0 = fd.define_tensor(shape=[1, -1], contiguity=[None, None], dtype=DataType.Int, is_cpu=False)
    fd.add_output(tv0)

with FusionDefinition() as fd:
    nvfuser_fusion(fd)

inputs = [
    torch.randint(0, 50000, (1, 1), device='cuda'),
]
outputs = fd.execute(inputs)
```

```
  File "thunder.computation_2", line 23, in computation
  File "/opt/pytorch/lightning-thunder/thunder/executors/nvfuserex_impl.py", line 567, in __call__
    return fd.execute(
           ^^^^^^^^^^^
  File "/opt/pytorch/nvfuser/python/nvfuser_direct/__init__.py", line 369, in execute
    return self.fec.execute(
           ^^^^^^^^^^^^^^^^^
RuntimeError: Expected (stride)==(0) . Found 1 vs 0. Expecting an expanded dimension on dimension 1
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:253 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x94 (0x7bdb80145403 in /opt/pytorch/nvfuser/python/nvfuser_direct/../build/libnvfuser_codegen.so)
frame #1: <unknown function> + 0x17c3245 (0x7bdb80bc3245 in /opt/pytorch/nvfuser/python/nvfuser_direct/../build/libnvfuser_codegen.so)
```

`validateAllocationSizesAndStrides` used to require `stride==0` for an
expanded extent, but it may not be the case when `size==1`, in which
case `stride` should not matter. The updated behavior aligns with the
docstring
[here](https://github.com/Lightning-AI/lightning-thunder/blob/fb989d485cf50fcd7645d500fb229f28e318ce52/thunder/executors/nvfuserex_impl.py#L473-L475).

I came across this error when testing dynamic shapes support in Thunder.
See
https://github.com/Lightning-AI/lightning-thunder/issues/2742#issuecomment-3655616157
for the context.

---------

Co-authored-by: Masato Shinokawa <shino16@users.noreply.github.com>
Co-authored-by: jjsjann123 <jiej@nvidia.com>