Propagate symbolic scalars over segments (#5669)
Fixed `resolveScalarsInGroup` to add non-const integral scalar extents
as inputs, including those that are not fusion inputs (e.g. reshape/view
sizes from other tensors). Please let me know if my changes make sense,
or feel free to modify them.

This fixes the following error. I came across this when I was enabling
dynamic shapes in Thunder's NanoGPT backward test in
[`test_grads.py::test_populate_grads_block`](https://github.com/Lightning-AI/lightning-thunder/blob/172320d05e2d0fe3e2b2129aaacea1d83be7cb5e/thunder/tests/test_grad.py#L1697).

```py
import torch
from nvfuser_direct import FusionDefinition, DataType

def nvfuser_fusion(fd : FusionDefinition) -> None :
    tv_a = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    tv1 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    c7 = fd.define_scalar(None, dtype=DataType.Int)
    c8 = fd.define_scalar(None, dtype=DataType.Int)
    c9 = fd.define_scalar(None, dtype=DataType.Int)
    c10 = fd.define_scalar(None, dtype=DataType.Int)
    tv_b = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, False, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    tv3 = fd.ops.sum(tv_a, dims=[0, 1], dtype=DataType.Float)
    tv6 = fd.ops.permute(tv_b, dims=[0, 1, 3, 2])
    c25 = fd.ops.cast(c8, dtype=DataType.Index)
    c27 = fd.ops.cast(c10, dtype=DataType.Index)
    c11 = fd.ops.size(tv6, dim=0)
    c12 = fd.ops.size(tv6, dim=1)
    tv4 = fd.ops.reshape(tv1, new_shape=[c11, c25, c12, c27])
    tv5 = fd.ops.permute(tv4, dims=[0, 2, 1, 3])
    fd.add_output(tv3)
    fd.add_output(tv5)
    fd.add_output(tv6)


inputs = [
    torch.randn(16, 128, 12 * 64, device="cuda"),
    torch.randn(16, 128, 12 * 64, device="cuda"),
    16,
    128,
    12,
    64,
    torch.randn(16, 128, 12, 64, device="cuda").permute(0, 2, 1, 3),
]

with FusionDefinition() as fd:
    nvfuser_fusion(fd)
    fd.execute(inputs)

print("Done")
```

```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/wt/main.py", line 37, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/wt/nvfuser_direct/__init__.py", line 318, in execute
    return self.fec.execute(
           ^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/wt/main.py", line 37, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/wt/nvfuser_direct/__init__.py", line 318, in execute
    return self.fec.execute(
           ^^^^^^^^^^^^^^^^^
RuntimeError:  INTERNAL ASSERT FAILED at /opt/pytorch/nvfuser/wt/csrc/runtime/allocations.cpp:165, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Expected inferred_val.hasValue() . Could not launch kernel as program could not infer i12 (i12) for the buffer T6_g_float[iS40{i4}, iS38{i12}, iS37{i5}, iS39{( ceilDiv(i6, 12) )}]
Exception raised from inferShape at /opt/pytorch/nvfuser/wt/csrc/runtime/allocations.cpp:165 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x94 (0x7cad0b943b27 in /opt/pytorch/nvfuser/wt/nvfuser_direct/../build/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, long, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7a (0x7cad0b943c24 in /opt/pytorch/nvfuser/wt/nvfuser_direct/../build/libnvfuser_codegen.so)
frame #2: <unknown function> + 0x13ed088 (0x7cad0bfed088 in /opt/pytorch/nvfuser/wt/nvfuser_direct/../build/libnvfuser_codegen.so)
```

Its repro is added as a new test.

---------

Co-authored-by: Masato Shinokawa <shino16@users.noreply.github.com>