Disable C++23 test (#1153)
Seeing CI failure:
```C++
FAILED: lib/dynamic_type/CMakeFiles/test_dynamic_type_23.dir/test/ForAllTypes.cpp.o 
/usr/bin/clang++  -I/home/runner/work/Fuser/Fuser/cmake/../third_party/benchmark/include -I/home/runner/work/Fuser/Fuser/lib/dynamic_type/src -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/googletest/googlemock/include -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/googletest/googletest/include -isystem /home/runner/work/Fuser/Fuser/cmake/../third_party/flatbuffers/include -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googletest/include -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googletest -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googlemock/include -isystem /home/runner/work/Fuser/Fuser/third_party/googletest/googlemock -Wno-psabi -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -DNDEBUG -std=gnu++2b -MD -MT lib/dynamic_type/CMakeFiles/test_dynamic_type_23.dir/test/ForAllTypes.cpp.o -MF lib/dynamic_type/CMakeFiles/test_dynamic_type_23.dir/test/ForAllTypes.cpp.o.d -o lib/dynamic_type/CMakeFiles/test_dynamic_type_23.dir/test/ForAllTypes.cpp.o -c /home/runner/work/Fuser/Fuser/lib/dynamic_type/test/ForAllTypes.cpp
In file included from /home/runner/work/Fuser/Fuser/lib/dynamic_type/test/ForAllTypes.cpp:9:
In file included from /home/runner/work/Fuser/Fuser/lib/dynamic_type/src/dynamic_type/type_traits.h:10:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/tuple:44:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_util.h:34:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_base.h:37:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_iterator.h:2618:35: error: missing 'typename' prior to dependent type name 'iterator_traits<_It>::iterator_category'
      { using iterator_category = iterator_traits<_It>::iterator_category; };
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
which pretty much looks like a compiler or standard library bug.

The purpose of adding C++23 test was to make sure we do not use any
feature that is deprecated in C++23, but if a compiler bug is failing
the CI, we are not interested in workaround it.

See also:
https://github.com/NVIDIA/Fuser/pull/1150#issuecomment-1781443087